"""Add order field to prompts table

Revision ID: 7900128ca2d5
Revises: 
Create Date: 2025-08-03 00:12:43.238817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7900128ca2d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('order', sa.Integer(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_prompts_order'), 'prompts', ['order'], unique=False)
    
    # Update existing prompts with sequential order based on creation date
    op.execute("""
        UPDATE prompts 
        SET "order" = (
            SELECT row_num 
            FROM (
                SELECT id, ROW_NUMBER() OVER (ORDER BY created_at ASC) as row_num 
                FROM prompts
            ) AS subquery 
            WHERE prompts.id = subquery.id
        )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompts_order'), table_name='prompts')
    op.drop_column('prompts', 'order')
    # ### end Alembic commands ###
