"""Add attached_prompts table

Revision ID: add_attached_prompts_table
Revises: 7900128ca2d5
Create Date: 2025-01-27 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_attached_prompts_table'
down_revision: Union[str, Sequence[str], None] = '7900128ca2d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attached_prompts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('main_prompt_id', sa.Integer(), nullable=False),
        sa.Column('attached_prompt_id', sa.Integer(), nullable=False),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['attached_prompt_id'], ['prompts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['main_prompt_id'], ['prompts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('main_prompt_id', 'attached_prompt_id', name='unique_attached_prompt')
    )
    op.create_index(op.f('ix_attached_prompts_id'), 'attached_prompts', ['id'], unique=False)
    op.create_index(op.f('ix_attached_prompts_main_prompt_id'), 'attached_prompts', ['main_prompt_id'], unique=False)
    op.create_index(op.f('ix_attached_prompts_attached_prompt_id'), 'attached_prompts', ['attached_prompt_id'], unique=False)
    op.create_index(op.f('ix_attached_prompts_order'), 'attached_prompts', ['order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attached_prompts_order'), table_name='attached_prompts')
    op.drop_index(op.f('ix_attached_prompts_attached_prompt_id'), table_name='attached_prompts')
    op.drop_index(op.f('ix_attached_prompts_main_prompt_id'), table_name='attached_prompts')
    op.drop_index(op.f('ix_attached_prompts_id'), table_name='attached_prompts')
    op.drop_table('attached_prompts')
    # ### end Alembic commands ### 